title: "Evan Hildreth"
author: "Evan Hildreth"
description: "Software developer and creative analyst in Greenville, SC"
baseurl: ""
url: "https://oddevan.github.io"
email: "me@eph.me"
microblog_user: "oddevan"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
paginate: 20
paginate_path: "/page/:num/"
timezone: America/New_York # A list of all available values can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

highlighter: "rouge"
markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap
  - jekyll-seo-tags

twitter:
  username: oddevan

social:
  name: Evan Hildreth
  links:
    - https://twitter.com/oddevan
    - https://www.facebook.com/evan.hildreth
    - https://www.linkedin.com/in/EvanHildreth
    - https://youtube.com/oddevan
    - https://github.com/oddevan
    - https://keybase.io/oddevan
    - https://paperairplanemob.tumblr.com